config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  get "home/about" => "homes#about"
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show, :edit, :update, :create, :index]
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
  validates :body,    length: { maximum: 200 }

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy



  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    @book.user_id = current_user.id
    @user = User.find(@book.user_id)
    @users = User.all
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render "index"
    end
  end

  def index
    @book = Book.new
    @user = User.find(current_user.id)
    @books = Book.all
    @users = User.all
    session['user'] = "books-index"
  end

  def show
    @book2 = Book.find(params[:id])
    @book = Book.new
    @user = User.find(@book2.user_id)
    @book_comment = BookComment.new
    @book_comments = BookComment.all
    session['user'] = "books-show"
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<main>
  <p id=notice><%= notice %></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>Editing Book</h2>
        <div id="error_explanation">
          <% if @book.errors.any? %>
            <h3>
              <%= @book.errors.count %>errors prohibited this user from being saved:
            </h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        
        <%= form_with model:@book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, id:"inputTitle", class: "form-control book_title"%>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, id:"inputOpinion", class: "form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book",class: "btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id=notice><%= notice %></p>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation">
      <% if @book.errors.any? %>
        <h3>
          <%= @book.errors.count %>errors prohibited this user from being saved:
        </h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class=mt-3>New book</h2>
        <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <% user.books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(user.id) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td>
                  <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      ♥<%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      ♡<%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% end %>
                </td>
                <td>
                  <div class="comments">
                  <p>コメント件数：<%= book.book_comments.count %></p>
                  </div>
                </td>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id=notice><%= notice %></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
            <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class=mt-3>New book</h2>
        <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book2.title, book_path %>
            </td>
            <td>
              <%= @book2.body %>
            </td>
            <td>
              <% if @book2.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book2), method: :delete do %>
                    ♥<%= @book2.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(@book2), method: :post do %>
                    ♡<%= @book2.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <div class="comments">
                <p>コメント件数：<%= @book2.book_comments.count %></p>
              </div>
            </td>
            <% if(current_user.id == @user.id) %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book2.id), class: "btn btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to 'Destroy', book_path(@book2.id), method: :DELETE, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
            </td>
            <% end %>
          </tr>
        </table>
        <div class="comments">
          <% @book_comments.each do |book_comment| %>
           <% if book_comment.book_id == @book2.id %>
              <p><%= book_comment.comment %>
              <% if current_user.id == book_comment.user_id %>
                <%= link_to 'Destroy', book_book_comment_path(@book2.id, book_comment.id), method: :DELETE, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
              <% end %>
              </p>
            <% end %>
          <% end %>
        </div>
        <div class="new-comment">
        <%= form_with(model:[@book2, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, placeholder: "コメントをここに", size: "50x5" %>
          <%= f.submit "Create Book comment" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</main>